---
title: "General Civi Activity Across All Programs"
author: "by Robert Janikowski"
output: pdf_document
header-includes:
  - \usepackage{booktabs}
fig_crop: no
date: '2022-6-13'
geometry: "left=1cm,right=1cm,top=1cm,bottom=1cm"
classoption: landscape, a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("reticulate")) {
install.packages("reticulate")
library(reticulate)
}
if (!require("ggplot2")) {
install.packages("ggplot2")
library(ggplot2)
}
if (!require("tidyverse")) {
install.packages("tidyverse")
library(tidyverse)
}
if (!require("RColorBrewer")) {
install.packages("RColorBrewer")
library(RColorBrewer)
}
if (!require("ggpubr")) {
install.packages("ggpubr")
library(ggpubr)
}
if (!require("grid")) {
install.packages("grid")
library(grid)
}
if (!require("extrafont")) {
install.packages("extrafont")
library(extrafont)
}
if (!require("scales")) {
install.packages("scales")
library(scales)
}
if (!require("knitr")) {
install.packages("knitr")
library(knitr)
}
if (!require("data.table")) {
  install.packages("data.table")
  library(data.table)
}
if (!require("kableExtra")) {
  install.packages("kableExtra")
  library(kableExtra)
}

#font_import(pattern = 'RUBIK')
#font_import(path = "C:/Users/rjanikowski/AppData/Local/Microsoft/Windows/Fonts", pattern = ".TTF")

#py_install("pandas")
#tinytex::install_tinytex()
source_python('GeneralActivityPrep_python_script.py')
#py_run_file('GeneralActivityPrep_python_script.py')
```
\newpage

```{r eval = FALSE, echo = FALSE}
#tables showing breakdown of included and excluded activity lists

kable(pivot2)
kable(pivot3)
```


```{r eval = FALSE, echo = FALSE}
#test graph (singular and does not print)
groupdf = df
groupdf = filter(groupdf, Staff_ClinicType == "Youth Health Centre")
colourCount = length(unique(groupdf$Contact_Name))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))


stackdf = groupdf %>% count(Contact_Name,Activity_Type)
totaldf = groupdf %>% count(Activity_Type)
names(totaldf)[2] = 't'
totaldf = totaldf %>% arrange(desc(t))
stackdf = merge(stackdf,totaldf)

if (nrow(totaldf) >= 75) {
  totaldf = totaldf %>% add_column(Top = NA)
  totaldf[1:floor(nrow(totaldf)/2),"Top"] = "yes"
  stackdf = merge(stackdf,totaldf)
  
  topdf =  stackdf %>% filter(!Top %in% c('yes'))
  
  (ggplot(topdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 1") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1))) + coord_flip() %>% print()
  
  Sys.sleep(1)
  
  bottomdf =  stackdf %>% filter(Top %in% c('yes'))
  
  (ggplot(bottomdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 2") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1))) + coord_flip() %>% print()
} else {
  
   (ggplot(stackdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 1") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1))) + coord_flip() %>% print()
  
}
```
```{r eval = FALSE, echo = FALSE, results='asis', warning = F}
df_freqTable = filter(df, Staff_ClinicType == "Youth Health Centre")
freqTable = sort(table(df_freqTable$Activity_Type), decreasing = TRUE)
#kable(freqTable, col.names = c(paste(clinicType, " Activities"), "Frequency"))

freqTable = as.data.frame(freqTable)

numCount = count(freqTable)
modCount = numCount %% 45
divisor = as.integer((numCount - modCount)/45)

if (divisor > 3) {
  divisor = 3
}

kableList = c()
minRange = 1
maxRange = 45

for (i in 1:divisor) {
  kable = kable(freqTable[minRange:maxRange,], format = 'latex', col.names = c(paste("Youth Health Centre", " Activities", i), "Frequency"))
  kableList = append(kableList, kable)
  
  minRange = minRange + 45
  maxRange = maxRange +45
  
}

catVector = c("\\begin{table}[h] \\centering ")

for (table in kableList) {
  catVector = append(catVector, table)
  catVector = append(catVector, "\\hspace{1cm} \\centering ")
}

catVector = append(catVector, "\\caption{My tables} \\end{table}")

cat(catVector)


#have to consruct cat with for loop


#knitr::kable(list(freqTable[1:45,], freqTable[46:90,]), col.names = c(paste("Youth Health Centre", " Activities"), "Frequency"), booktabs = TRUE)

#(knitr::kable(freqTable, col.names = c(paste(clinicType, " Activities"), "Frequency"))) %>% print

```


```{r eval = TRUE, echo = FALSE, fig.align = "center", fig.height = 10, fig.width = 14, out.width = "8.5in", results='asis'}
## this loop iterates through each clinicType and prints different graphs based on activity data from the clinicType


#staffClinicList = staffClinicList[0:1]

for (clinicType in staffClinicList)
{
  df_freqTable = filter(df, Staff_ClinicType == clinicType)
  freqTable = sort(table(df_freqTable$Activity_Type), decreasing = TRUE)
  
  freqTable = as.data.frame(freqTable)
  
  numCount = count(freqTable)
  modCount = numCount %% 40
  divisor = as.integer((numCount - modCount)/40)
  
  if (divisor > 3) {
    divisor = 3
  }
  
  kableList = c()
  minRange = 1
  maxRange = 40
  
  for (i in 1:divisor) {
    #kable = kable(freqTable[minRange:maxRange,], format = 'latex', col.names = c(paste(clinicType, " Activities", i), "Frequency"))
    #kable = kable(freqTable[minRange:maxRange,], col.names = c(paste(clinicType, " Activities", i), "Frequency"))
    kable = freqTable[minRange:maxRange,]
    kableList = append(kableList, kable)
    
    minRange = minRange + 40
    maxRange = maxRange +40
    
  }
  
  #catVector = c("\\begin{table}[h] \\centering ")
  
  #for (table in kableList) {
  #  catVector = append(catVector, table)
  #  catVector = append(catVector, "\\hspace{1cm} \\centering ")
  #}
  
  #catVector = append(catVector, "\\caption{My tables} \\end{table}")
  
  cat(kable(kableList, caption = paste(clinicType, "Activity Frequencies"), booktabs = TRUE, format = "latex", valign = 't', col.names = NULL) %>% kable_styling(latex_options = "HOLD_position"))
  cat("\n")
  
  
  Sys.sleep(1)
  
  #beginning of graphs
  groupdf = df [!duplicated(df[c("Contact_Name","StaffDate")]),]
  groupdf = filter(groupdf, Staff_ClinicType == clinicType)
  
  colourCount = length(unique(groupdf$Contact_Name))
  getPalette = colorRampPalette(brewer.pal(9, "Set1"))
  
  (ggplot(filter(df, Staff_ClinicType == clinicType)) +aes(x = lubridate::floor_date(Date, "month")) + geom_bar() +ggtitle(clinicType) +labs(y= "Overall Activity Count", x = "Date(month)", subtitle = "Overall Activity Count") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black"))) %>% print()
  Sys.sleep(1)
  
  (ggplot(groupdf, aes(x =StaffDate, y=staff_activity_count, group = groupdf$Contact_Name, colour = groupdf$Contact_Name)) + geom_line(size=1) + geom_point( size=2, shape=21, fill="white") + scale_colour_manual(values=getPalette(colourCount)) +theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank()) + guides(colour = guide_legend(title.position = "bottom"),legend.key.size = unit(2,"line")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (line)") + expand_limits(x = unique(df$StaffDate)) + theme(plot.title = element_text(size = 25, face = "bold",hjust = 0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")))  %>% print()
  
  Sys.sleep(1)
  
  (ggplot(groupdf, aes(fill=Contact_Name, y=staff_activity_count, x=StaffDate)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(2,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked)") + expand_limits(x = unique(df$StaffDate)) + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")))  %>% print()
  
  Sys.sleep(1)

  
### stacked side graph
groupdf = df
groupdf = filter(groupdf, Staff_ClinicType == clinicType)
colourCount = length(unique(groupdf$Contact_Name))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

stackdf = groupdf %>% count(Contact_Name,Activity_Type)
totaldf = groupdf %>% count(Activity_Type)
names(totaldf)[2] = 't'
totaldf = totaldf %>% arrange(desc(t))
stackdf = merge(stackdf,totaldf)

## if there are more than 75 unique activities, activities are split into two different graphs
if (nrow(totaldf) >= 75) {
  totaldf = totaldf %>% add_column(Top = NA)
  totaldf[1:floor(nrow(totaldf)/2),"Top"] = "yes"
  stackdf = merge(stackdf,totaldf)
  
  topdf =  stackdf %>% filter(!Top %in% c('yes'))
  
  (ggplot(topdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 1") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1)) + coord_flip()) %>% print()
  
  Sys.sleep(1)
  
  bottomdf =  stackdf %>% filter(Top %in% c('yes'))
  
  (ggplot(bottomdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 2") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1)) + coord_flip() )%>% print()
  
  Sys.sleep(1)
} else {
  
   (ggplot(stackdf, aes(x=reorder(Activity_Type,t), y=n, fill=Contact_Name)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position = "bottom",legend.text=ggplot2::element_text(size=8),legend.title=element_blank(),legend.key.size = unit(1.5,"line")) + guides(colour = guide_legend(title.position = "bottom")) + ggtitle(clinicType) + labs(y= "Activity Count by Staff Member", x = "Date(month)", subtitle = "Civi Activity By Staff Member (stacked) Part 1") + theme(plot.title = element_text(size = 25, face = "bold", hjust=0.5)) + theme(plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="black")) + theme(plot.margin = margin(t=-1, r=-1, b=-1, l=-1)) + coord_flip()) %>% print()
  
  Sys.sleep(1)
  
}
  
}
```




